CREATE TABLE STUDENT( 
    ID INTEGER NOT NULL, 
    FIRST_NAME VARCHAR(255), 
    LAST_NAME VARCHAR(255), 
    YEAR_OF_STUDY VARCHAR(255) 
);

INSERT INTO STUDENT(ID,FIRST_NAME,LAST_NAME,YEAR_OF_STUDY) VALUES (2,"Jan","Kowalski","1");