---
- hosts: app_nodes
  become: yes
  vars:
    jar_location: ../studentCrud/target/studentcrudapp-0.0.1-SNAPSHOT.jar
    app_location: /opt/studentapp/studentapp.jar
    app_user: studentapp
  tasks:
    - name: "install jre"
      yum:
        name: java-1.8.0-openjdk
        state: present
    - name: "create path"
      file:
        path: /opt/studentapp
        state: directory
    - name: "copy .jar to remote machine"
      copy:
        src: "{{jar_location}}"
        dest: "{{app_location}}"
    - name: "create user for service"
      user:
        name: "{{app_user}}"
    - name: "copy systemd config"
      template:
        src: template/studentapp.service
        dest: /etc/systemd/system/studentapp.service
    - name: "start service"
      systemd:
        name: "studentapp.service"
        daemon_reload: yes
        state: restarted

- hosts: proxy_nodes
  become: yes
  vars:
    nginx_path: 18.184.175.90 
    app_private_path: 172.31.24.121
  tasks:
    - yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
    - name: Install nginx web server
      yum:
        name: nginx
        state: present
    - name: Add nginx.conf file
      template:
        src: template/temp_nginx.conf
        dest: /etc/nginx/conf.d/my_nginx.conf
    - service:
        name: nginx
        state: restarted
    