---
    - yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
    - name: Install nginx web server
      yum:
        name: nginx
        state: present
    - name: Add nginx.conf file
      template:
        src: template/temp_nginx.conf
        dest: /etc/nginx/conf.d/my_nginx.conf
    - service:
        name: nginx
        state: restarted
    - yum:
        name: python2-certbot-nginx
        state: present
    - shell: "sudo certbot -i nginx -d '{{domain}}' --nginx -m '{{email}}' --agree-tos --redirect"
